name: Build mpv

on:
  workflow_dispatch:

jobs:
  build:
    #runs-on: ubuntu-16.04
    runs-on: ubuntu-latest
    container: 'wachii/ubuntu-qt:16.04

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #- name: Install build dependencies
      #  run: sudo apt-get install `cat build_depends_xenial.txt`

      - name: Install devscripts
        run: |
            sudo apt-get update
            sudo apt-get install devscripts equivs
      
      - name: Remove unavailable dependencies
        run: |
            sed -i '/libdav1d-dev/d' debian/control
            sed -i '/enable-libdav1d/d' debian/rules
            
      - name: Use openssl
        run: |
            sed -e 's/libgnutls-dev | libgnutls28-dev/libssl-dev/' -i debian/control
            sed -e 's/--enable-gnutls/--enable-openssl/' -i debian/rules
            sed -e 's/--enable-gpl/--enable-nonfree/' -i debian/rules

      - name: Install build dependencies
        run: |
            mk-build-deps
            ls *.deb
            dpkg --info ./mpv-build-deps*.deb
            sudo apt-get install ./mpv-build-deps*.deb --no-install-recommends --yes
        
      - name: Install openssl&libssl-dev
        run: |
            sudo apt-get install -y --allow-downgrades openssl=1.0.2g-1ubuntu4.19 libssl-dev=1.0.2g-1ubuntu4.19
            dpkg -l openssl libssl-dev | grep '^ii' | cut -c5-

      - name: Configure
        run: |
            ./use-ffmpeg-release
            ./use-libass-custom 0.14.0
            #./use-libass-custom 30bd3d34d32cebeb7b1af6b9e77f617ef1d2bb9a
            ./use-mpv-release
            echo "--enable-gl-x11 --enable-libmpv-shared" > mpv_options

      - name: Update sources
        run: ./update

      - name: Build libass
        run: |
            scripts/libass-config
            scripts/libass-build

      - name: Build ffmpeg
        run: |
            scripts/ffmpeg-config
            scripts/ffmpeg-build

      - name: Build mpv
        run: |
            scripts/mpv-config
            scripts/mpv-build
            strip mpv/build/mpv

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: mpv
          path: mpv/build/
