name: Build mpv deb

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: 'xenial', os: 'ubuntu-16.04' }
          #- { name: 'bionic', os: 'ubuntu-18.04' }
          - { name: 'focal', os: 'ubuntu-20.04' }
          
    runs-on: ${{ matrix.config.os }}

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install openssl and libssl-dev
        run: |
            sudo apt-get install -y --allow-downgrades openssl=1.0.2g-1ubuntu4.19 libssl-dev=1.0.2g-1ubuntu4.19
            dpkg -l openssl libssl-dev | grep '^ii' | cut -c5-
        if: ${{ matrix.config.name == 'xenial' }}

      - name: Install devscripts
        run: sudo apt-get install devscripts equivs
      
      - name: Add repository
        run: |
            sudo add-apt-repository ppa:mc3man/mpv-tests --yes
            sudo apt-get update
        if: ${{ matrix.config.name == 'xenial' }}

      - name: Install build dependencies
        run: |
            mk-build-deps
            ls *.deb
            dpkg --info ./mpv-build-deps*.deb
            sudo apt-get install ./mpv-build-deps*.deb --no-install-recommends --yes
     
      - name: Configure sources
        run: |
            ./use-ffmpeg-release
            ./use-libass-custom 0.14.0
            #./use-libass-custom 30bd3d34d32cebeb7b1af6b9e77f617ef1d2bb9a
            ./use-mpv-release

      - name: Update sources
        run: ./update
      
      - name: Build package
        run: |
            dpkg-buildpackage -uc -us -b -j4
            mv ../mpv_*.deb .
            ls -l mpv_*.deb
        
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: mpv-${{ matrix.config.name }}
          path: ./mpv_*.deb
  
