name: Terminal

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
